name: Generate Manifest
on:
  push:
    paths:
      - 'plugin_urls.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./ci/envs/requirements-intake.txt
      - name: Run Intake script
        run: python ./ci/src/intake.py
      - name: Update plugin manifest
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git add plugins.json
          git commit -m "Update manifest"
          git push
